Add `tap 'heroku/brew'` to install heroku now
I had a version from Fall last year so when I logged in it failed with the following error:

```
> heroku login
Warning: Unsupported install. Install heroku with `brew install heroku/brew/heroku`
TypeError: Cannot read property '' of undefined
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:1
```

Checking the https://cli.heroku.com page shows that installing from Homebrew requires the tap now:

> brew tap heroku/brew && brew install heroku